/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteRouteImport } from './routes/_appLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutSettingsRouteImport } from './routes/_appLayout/settings'
import { Route as AppLayoutProfileRouteImport } from './routes/_appLayout/profile'
import { Route as AppLayoutInboxRouteImport } from './routes/_appLayout/inbox'
import { Route as AppLayoutComposeRouteImport } from './routes/_appLayout/compose'

const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutSettingsRoute = AppLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutProfileRoute = AppLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutInboxRoute = AppLayoutInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutComposeRoute = AppLayoutComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof AppLayoutComposeRoute
  '/inbox': typeof AppLayoutInboxRoute
  '/profile': typeof AppLayoutProfileRoute
  '/settings': typeof AppLayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof AppLayoutComposeRoute
  '/inbox': typeof AppLayoutInboxRoute
  '/profile': typeof AppLayoutProfileRoute
  '/settings': typeof AppLayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/_appLayout/compose': typeof AppLayoutComposeRoute
  '/_appLayout/inbox': typeof AppLayoutInboxRoute
  '/_appLayout/profile': typeof AppLayoutProfileRoute
  '/_appLayout/settings': typeof AppLayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compose' | '/inbox' | '/profile' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compose' | '/inbox' | '/profile' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_appLayout'
    | '/_appLayout/compose'
    | '/_appLayout/inbox'
    | '/_appLayout/profile'
    | '/_appLayout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/settings': {
      id: '/_appLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppLayoutSettingsRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/profile': {
      id: '/_appLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppLayoutProfileRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/inbox': {
      id: '/_appLayout/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppLayoutInboxRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/compose': {
      id: '/_appLayout/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppLayoutComposeRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutComposeRoute: typeof AppLayoutComposeRoute
  AppLayoutInboxRoute: typeof AppLayoutInboxRoute
  AppLayoutProfileRoute: typeof AppLayoutProfileRoute
  AppLayoutSettingsRoute: typeof AppLayoutSettingsRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutComposeRoute: AppLayoutComposeRoute,
  AppLayoutInboxRoute: AppLayoutInboxRoute,
  AppLayoutProfileRoute: AppLayoutProfileRoute,
  AppLayoutSettingsRoute: AppLayoutSettingsRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
