// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Message struct {
	ID        int64
	UserID    int64
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Link      string
	Password  string
	CreatedAt time.Time
}
