// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Message struct {
	ID        int64
	UserID    int64
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int64
	UserName  string
	Email     string
	Link      string
	Password  string
	CreatedAt sql.NullTime
}
