// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_name, email, password, link
) VALUES (
    ?1, ?2, ?3, ?4
) RETURNING id, user_name, email, link, password, created_at
`

type CreateUserParams struct {
	UserName string
	Email    string
	Password string
	Link     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Link,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Link,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, user_name, password, email, link FROM users WHERE user_name = ?1
`

type GetUserByUsernameRow struct {
	ID       int64
	UserName string
	Password string
	Email    string
	Link     string
}

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, userName)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Password,
		&i.Email,
		&i.Link,
	)
	return i, err
}
