name: API CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.5"

      - name: Setup moon and proto toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Run Tests
        run: moon run :test-coverage

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: moon run :gosec
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.5"

      - name: Setup moon and proto toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Run Style
        run: moon run :format

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run:  moon run :staticcheck
