name: api CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup moon and proto toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: apps/api/go.mod
          cache-dependency-path: apps/api/go.sum

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run moon CI (lint)
        run: moon ci api:lint

      - name: Run moon CI (test)
        run: moon ci api:format

      - name: Run moon CI (build)
        run: moon ci api:tidy

      - name: Run moon CI (migrate-up)
        run: moon ci api:migrate-up

      - name: Run moon CI (build)
        run: moon ci api:build
